// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYbHAA0JnH6fKCdMea6Ayzx7PZ02tJFZA',
    appId: '1:283354073361:web:cf5e4479dfd6672f9264b0',
    messagingSenderId: '283354073361',
    projectId: 'budget-tracker-ffac4',
    authDomain: 'budget-tracker-ffac4.firebaseapp.com',
    storageBucket: 'budget-tracker-ffac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWZ8U-Mka-HNFqnXJUVZOaeAokl5If78',
    appId: '1:283354073361:android:419fe017f46169669264b0',
    messagingSenderId: '283354073361',
    projectId: 'budget-tracker-ffac4',
    storageBucket: 'budget-tracker-ffac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBquye5Qtlp_9POEbCIGiEvy3JkJWg5K-4',
    appId: '1:283354073361:ios:0c0f3d76c46d365b9264b0',
    messagingSenderId: '283354073361',
    projectId: 'budget-tracker-ffac4',
    storageBucket: 'budget-tracker-ffac4.appspot.com',
    iosClientId:
        '283354073361-4l8t0le48dl5lml2hdlrdh2646o705bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBquye5Qtlp_9POEbCIGiEvy3JkJWg5K-4',
    appId: '1:283354073361:ios:25aad610a52086ae9264b0',
    messagingSenderId: '283354073361',
    projectId: 'budget-tracker-ffac4',
    storageBucket: 'budget-tracker-ffac4.appspot.com',
    iosClientId:
        '283354073361-rh9nb6rb7k5qaj50m80mqcn56s4hga6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBudgetApp.RunnerTests',
  );
}
